version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src:/code/src
      - ../data/media:/code/data/media
      - ../data/uploads:/code/data/uploads
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../data/db/postgres:/var/lib/postgresql/data/:z
